// Fixed books list — same for ALL students/batches.
// Keys MUST match what Wix backend stores in BookScores collection.
export const BOOKS = [
  {
    key:         'marie_mysterious_rock',
    title:       "Marie's Mysterious Rock",
    author:      'Marie Curie',
    subtitle:    'Humans of Science STEM Series',
    emoji:       '🪨',
    description: 'Discover the secrets of the fun-filled radioactive world',
    color:       '#E8A020',
    colorDark:   '#B57A10',
    bgGradient:  'linear-gradient(135deg, #F4C355, #E8A020)',
  },
  {
    key:         'einstein_wonders',
    title:       "Einstein's Wonders",
    author:      'Albert Einstein',
    subtitle:    'Humans of Science STEM Series',
    emoji:       '⚡',
    description: 'Hop on a journey of wonder and discover the power of imagination',
    color:       '#7B52C8',
    colorDark:   '#5A3A9A',
    bgGradient:  'linear-gradient(135deg, #A07EE8, #7B52C8)',
  },
  {
    key:         'archimedes_explorations',
    title:       "Archimedes' Explorations",
    author:      'Archimedes',
    subtitle:    'Humans of Science STEM Series',
    emoji:       '🌊',
    description: 'A journey through the life and wonders of Archimedes',
    color:       '#1AAA78',
    colorDark:   '#128058',
    bgGradient:  'linear-gradient(135deg, #3DD4A2, #1AAA78)',
  },
  {
    key:         'katherine_courage',
    title:       "Katherine's Courage",
    author:      'Katherine Johnson',
    subtitle:    'Humans of Science STEM Series',
    emoji:       '🚀',
    description: 'The inspiring story of a mathematician who reached the stars',
    color:       '#E84E9B',
    colorDark:   '#B83078',
    bgGradient:  'linear-gradient(135deg, #F585C0, #E84E9B)',
  },
  {
    key:         'ada_algorithm',
    title:       "Ada's Algorithm",
    author:      'Ada Lovelace',
    subtitle:    'Humans of Science STEM Series',
    emoji:       '💻',
    description: 'Meet the first computer programmer and her brilliant mind',
    color:       '#3B6DD4',
    colorDark:   '#2A4FA0',
    bgGradient:  'linear-gradient(135deg, #6B9FFF, #3B6DD4)',
  },
  {
    key:         'darwin_discovery',
    title:       "Darwin's Discovery",
    author:      'Charles Darwin',
    subtitle:    'Humans of Science STEM Series',
    emoji:       '🦋',
    description: 'Explore the natural world through the eyes of evolution',
    color:       '#5A9E3A',
    colorDark:   '#3E7228',
    bgGradient:  'linear-gradient(135deg, #88CC60, #5A9E3A)',
  },
  {
    key:         'newton_motion',
    title:       "Newton's Motion",
    author:      'Isaac Newton',
    subtitle:    'Humans of Science STEM Series',
    emoji:       '🍎',
    description: 'Discover the laws that govern the universe around us',
    color:       '#2255AA',
    colorDark:   '#163A7A',
    bgGradient:  'linear-gradient(135deg, #5585DD, #2255AA)',
  },
  {
    key:         'curie_radioactivity',
    title:       "Curie's Radioactivity",
    author:      'Marie Curie',
    subtitle:    'Humans of Science STEM Series',
    emoji:       '⚗️',
    description: 'The incredible science of radiation and pioneering discovery',
    color:       '#55AA22',
    colorDark:   '#3A7A14',
    bgGradient:  'linear-gradient(135deg, #88DD44, #55AA22)',
  },
  {
    key:         'faraday_fields',
    title:       "Faraday's Fields",
    author:      'Michael Faraday',
    subtitle:    'Humans of Science STEM Series',
    emoji:       '🔋',
    description: 'Journey into the invisible world of electricity and magnetism',
    color:       '#0891B2',
    colorDark:   '#066B88',
    bgGradient:  'linear-gradient(135deg, #38BDF8, #0891B2)',
  },
  {
    key:         'tesla_electricity',
    title:       "Tesla's Electricity",
    author:      'Nikola Tesla',
    subtitle:    'Humans of Science STEM Series',
    emoji:       '🔬',
    description: 'A journey through sparks, science and imagination',
    color:       '#7C3AED',
    colorDark:   '#5B21B6',
    bgGradient:  'linear-gradient(135deg, #A78BFA, #7C3AED)',
  },
  {
    key:         'hawking_universe',
    title:       "Hawking's Universe",
    author:      'Stephen Hawking',
    subtitle:    'Humans of Science STEM Series',
    emoji:       '🌌',
    description: 'Explore black holes, time, and the wonders of the cosmos',
    color:       '#1E3A5F',
    colorDark:   '#0F1F33',
    bgGradient:  'linear-gradient(135deg, #4A90D9, #1E3A5F)',
  },
];
